name: day_1_flutter_test
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  flutter_animate: ^4.2.0
  intl: ^0.18.0
  cloud_firestore: ^4.15.0  # Update ke versi terbaru
  firebase_auth: ^4.17.0  # Update ke versi terbaru
  provider: ^6.1.0  # Perbaikan versi

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/coffee-shop/bg.png
    - assets/coffee-shop/promo.png
    - assets/coffee-shop/promo2.jpeg
    - assets/coffee-shop/promo3.jpeg
    - assets/coffee-shop/promomax.png
    - assets/coffee-shop/caffe_mocha.png
    - assets/coffee-shop/flat_white.jpg
    - assets/coffee-shop/me.jpg
    - assets/coffee-shop/minara.png
    - assets/coffee-shop/latte.jpeg
    - assets/coffee-shop/cappuccino.jpeg
    - assets/coffee-shop/espresso.jpeg
    - assets/coffee-shop/mocha.jpeg
